# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 624adab2a62d3f0a79033761afa05c8eafd8b22da1e1fc5ad67131b798a9d4e67bc5348991d0d7ba91c7ff7514daf8dec6152f35e9f96cebe3177f2b0a834711

test:
  secret_key_base: d10a3babe9f8c7942361f160bb13d99ee4d7934c3e5fc2eee9ff88e1cb40e7d08f1a0188173ab762002ac18984c16836ccae25a5c3fe37b03c47120c0553f775

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
